#!/usr/bin/env sh

# The executable used is 'lein2' for compatiblity with Travis CI.
# Make a local symlink if yours is just named 'lein'
lein2 test clj-webdriver.test.firefox && lein2 test clj-webdriver.test.phantomjs
