#!/usr/bin/env bash

#
# Usage: test <case>
#

source $(dirname $0)/util

EXPECTED_ARGS=1
E_BADARGS=65

DO_showUsage() {
    echo "Usage: $(basename $0) {all|core|remote|taxi}"
    exit $E_BADARGS
}

if [ $# -ne $EXPECTED_ARGS ]; then
    DO_showUsage
fi

################################################################################

GRID_HOST_DEFAULT=127.0.0.1
# 3001 is default for regular API, so for testing we'll default to 3003
GRID_PORT_DEFAULT=3003

DO_testCore() {
    if [ $2 == "single" ]; then
        lein test clj-webdriver.test.chrome
    else
        lein test clj-webdriver.test.firefox
        lein test clj-webdriver.test.chrome
    fi
}

DO_testRemote() {
    echo -n "Please enter the ${txtund}${regblu}host${txtrst} on which your Grid hub is running: [${GRID_HOST_DEFAULT}] > "
    read WEBDRIVER_GRID_HOST
    if [ -z $WEBDRIVER_GRID_HOST ]; then
        export WEBDRIVER_GRID_HOST="${GRID_HOST_DEFAULT}"
    fi
    echo -n "Please enter the ${txtund}${regblu}port${txtrst} on which your Grid hub is listening: [${GRID_PORT_DEFAULT}] > "
    read WEBDRIVER_GRID_PORT
    if [ -z $WEBDRIVER_GRID_PORT ]; then
        export WEBDRIVER_GRID_PORT="${GRID_PORT_DEFAULT}"
    fi
    lein test clj-webdriver.test.remote-manual
    lein test clj-webdriver.test.remote
    lein test clj-webdriver.test.wire
}

DO_testTaxi() {
    lein midje clj-webdriver.test.taxi
}

case "$1" in
    all)
        DO_testCore
        DO_testRemote
        DO_testTaxi
        ;;
    core)
        DO_testCore
        ;;
    remote)
        DO_testRemote
        ;;
    taxi)
        DO_testTaxi
        ;;
    *)
        DO_showUsage
esac
        
